### ISSUE TITLE
Add python and docker to the dockerfile

### ISSUE THREAD

**Issue by jankatins** [soulteary/docker-cronicle#20]
I run cronicle on my NAS. I would like to run python scripts and access docker (e.g. by mounting the docker socket into the container in docker-compose).

Would it be possible to install python and docker (client) into the container?

If not: do you have an alternative to make runtime environments available in cronicle? Adding a new volume and installing it there and add it to the PATH in each script?

**Comment by luisccgoncalves** [comment]
This would be great.

Even adding bash support would be an improvement.

**Comment by scls19fr** [comment]
I noticed this other project https://github.com/bluet/docker-cronicle-docker/
but I haven't been able to make it works behind Traefik (facing "Waiting for master server..." message https://github.com/bluet/docker-cronicle-docker/issues/45 )
PS : you may be also interested by this discussion https://github.com/jhuckaby/Cronicle/discussions/736

**Comment by soulteary** [comment]
In the best practice of #9, there is some content that you can refer to about disassembling the specific execution process of Cornicle to an external docker container through webhook.

Of course, I think it is also necessary to update an article on how to repackage a suitable new docker image to use.

@jankatins @luisccgoncalves

**Comment by arseniov** [comment]
Wouldn't it be easy to just use a Dockerfile to build an image based on your requirements?

As an example:
```
FROM soulteary/cronicle:latest

RUN apk update && \
        apk add python3 py3-pip py3-requests py3-httplib2
```

And then update your docker-compose.yml **from this**:


```
services:
  cronicle:
    image: soulteary/cronicle:latest
    container_name: cronicle
    hostname: cronicle
    environment:
      - TZ=Europe/Rome
    ports:
      - "3012:3012"
```

**To this**:
```
services:
  cronicle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronicle
    hostname: cronicle
    environment:
      - TZ=Europe/Rome
    ports:
      - "3012:3012"
```
