### ISSUE TITLE
Config behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by acwebdesign** [soulteary/docker-cronicle#30]
Hi,
Tks for your work.
Just to share my experience with NPM
So here is my docker compose : 
```
services:
  cronicle:
    image: soulteary/cronicle:latest
    restart: always
    hostname: cronicle.ndd.tld
    container_name: cronicle
    ports:
      - 3012:3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
    extra_hosts:
      - "cronicle.ndd.tld:0.0.0.0"
    environment:
      - TZ=Europe/Paris
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
networks:
  default:
    name: mynetwork
    external: true
```
And the important thing is to activate websocket in NPM : 

![Image](https://github.com/user-attachments/assets/12fc84e3-18db-440a-be36-4e009afeed47)
Next step is ssl ^^
